import fs from "node:fs";
import path from "node:path";
import { saveJsonFile } from "../infra/json-file.js";
import { describeReadFailure } from "../infra/unreadable-source.js";
import { logWarn } from "../logger.js";
import {
  DEFAULT_OPENCLAW_BROWSER_COLOR,
  DEFAULT_OPENCLAW_BROWSER_PROFILE_NAME,
} from "./constants.js";

function decoratedMarkerPath(userDataDir: string) {
  return path.join(userDataDir, ".openclaw-profile-decorated");
}

type JsonRecordRead =
  | { status: "ok"; value: Record<string, unknown> }
  | { status: "absent" }
  | { status: "unreadable"; detail: string };

/**
 * "No file" (a fresh profile) and "a file that could not be read or parsed" are different
 * answers. Collapsing them made `?? {}` overwrite Chrome's `Preferences` — the only copy of the
 * profile's settings — with a two-key object, which is how a browser profile gets wiped.
 *
 * Callers must skip the write when this reports `unreadable`.
 */
function readJsonRecord(filePath: string): JsonRecordRead {
  let raw: string;
  try {
    raw = fs.readFileSync(filePath, "utf-8");
  } catch (err) {
    if (!fs.existsSync(filePath)) {
      return { status: "absent" };
    }
    const failure = describeReadFailure(err);
    logWarn(
      `[browser] cannot read ${filePath} (${failure.status}/${failure.code}); leaving it untouched`,
    );
    return { status: "unreadable", detail: `${failure.status}/${failure.code}` };
  }
  try {
    const parsed = JSON.parse(raw) as unknown;
    if (typeof parsed !== "object" || parsed === null || Array.isArray(parsed)) {
      logWarn(`[browser] ${filePath} is not a JSON object; leaving it untouched`);
      return { status: "unreadable", detail: "not-an-object" };
    }
    return { status: "ok", value: parsed as Record<string, unknown> };
  } catch {
    logWarn(`[browser] cannot parse ${filePath}; leaving it untouched`);
    return { status: "unreadable", detail: "parse-failed" };
  }
}

/** Read-only variant: "cannot see it" is answered as "not there yet", which is the safe
 * direction for the decoration checks — the caller then tries to decorate and bails out there. */
function safeReadJson(filePath: string): Record<string, unknown> | null {
  const result = readJsonRecord(filePath);
  return result.status === "ok" ? result.value : null;
}

function safeWriteJson(filePath: string, data: Record<string, unknown>) {
  // This writes Chrome's own `Preferences` file, which is a few hundred KB and the only copy of
  // the profile's settings. writeFileSync truncates first, so a crash mid-write left Chrome with
  // an unparseable profile — "safe" in name only. Replace it atomically instead.
  saveJsonFile(filePath, data);
}

function setDeep(obj: Record<string, unknown>, keys: string[], value: unknown) {
  let node: Record<string, unknown> = obj;
  for (const key of keys.slice(0, -1)) {
    const next = node[key];
    if (typeof next !== "object" || next === null || Array.isArray(next)) {
      node[key] = {};
    }
    node = node[key] as Record<string, unknown>;
  }
  node[keys[keys.length - 1] ?? ""] = value;
}

function parseHexRgbToSignedArgbInt(hex: string): number | null {
  const cleaned = hex.trim().replace(/^#/, "");
  if (!/^[0-9a-fA-F]{6}$/.test(cleaned)) {
    return null;
  }
  const rgb = Number.parseInt(cleaned, 16);
  const argbUnsigned = (0xff << 24) | rgb;
  // Chrome stores colors as signed 32-bit ints (SkColor).
  return argbUnsigned > 0x7fffffff ? argbUnsigned - 0x1_0000_0000 : argbUnsigned;
}

export function isProfileDecorated(
  userDataDir: string,
  desiredName: string,
  desiredColorHex: string,
): boolean {
  const desiredColorInt = parseHexRgbToSignedArgbInt(desiredColorHex);

  const localStatePath = path.join(userDataDir, "Local State");
  const preferencesPath = path.join(userDataDir, "Default", "Preferences");

  const localState = safeReadJson(localStatePath);
  const profile = localState?.profile;
  const infoCache =
    typeof profile === "object" && profile !== null && !Array.isArray(profile)
      ? (profile as Record<string, unknown>).info_cache
      : null;
  const info =
    typeof infoCache === "object" &&
    infoCache !== null &&
    !Array.isArray(infoCache) &&
    typeof (infoCache as Record<string, unknown>).Default === "object" &&
    (infoCache as Record<string, unknown>).Default !== null &&
    !Array.isArray((infoCache as Record<string, unknown>).Default)
      ? ((infoCache as Record<string, unknown>).Default as Record<string, unknown>)
      : null;

  const prefs = safeReadJson(preferencesPath);
  const browserTheme = (() => {
    const browser = prefs?.browser;
    const theme =
      typeof browser === "object" && browser !== null && !Array.isArray(browser)
        ? (browser as Record<string, unknown>).theme
        : null;
    return typeof theme === "object" && theme !== null && !Array.isArray(theme)
      ? (theme as Record<string, unknown>)
      : null;
  })();

  const autogeneratedTheme = (() => {
    const autogenerated = prefs?.autogenerated;
    const theme =
      typeof autogenerated === "object" && autogenerated !== null && !Array.isArray(autogenerated)
        ? (autogenerated as Record<string, unknown>).theme
        : null;
    return typeof theme === "object" && theme !== null && !Array.isArray(theme)
      ? (theme as Record<string, unknown>)
      : null;
  })();

  const nameOk = typeof info?.name === "string" ? info.name === desiredName : true;

  if (desiredColorInt == null) {
    // If the user provided a non-#RRGGBB value, we can only do best-effort.
    return nameOk;
  }

  const localSeedOk =
    typeof info?.profile_color_seed === "number"
      ? info.profile_color_seed === desiredColorInt
      : false;

  const prefOk =
    (typeof browserTheme?.user_color2 === "number" &&
      browserTheme.user_color2 === desiredColorInt) ||
    (typeof autogeneratedTheme?.color === "number" && autogeneratedTheme.color === desiredColorInt);

  return nameOk && localSeedOk && prefOk;
}

/**
 * Best-effort profile decoration (name + lobster-orange). Chrome preference keys
 * vary by version; we keep this conservative and idempotent.
 */
export function decorateOpenClawProfile(
  userDataDir: string,
  opts?: { name?: string; color?: string },
) {
  const desiredName = opts?.name ?? DEFAULT_OPENCLAW_BROWSER_PROFILE_NAME;
  const desiredColor = (opts?.color ?? DEFAULT_OPENCLAW_BROWSER_COLOR).toUpperCase();
  const desiredColorInt = parseHexRgbToSignedArgbInt(desiredColor);

  const localStatePath = path.join(userDataDir, "Local State");
  const preferencesPath = path.join(userDataDir, "Default", "Preferences");

  // If either file is there but unreadable, decorate nothing: writing a near-empty document over
  // half of a profile we cannot see is worse than a skipped round, and leaving the marker off
  // means the next run retries.
  const localStateRead = readJsonRecord(localStatePath);
  const preferencesRead = readJsonRecord(preferencesPath);
  if (localStateRead.status === "unreadable" || preferencesRead.status === "unreadable") {
    return;
  }
  const localState = localStateRead.status === "ok" ? localStateRead.value : {};
  // Common-ish shape: profile.info_cache.Default
  setDeep(localState, ["profile", "info_cache", "Default", "name"], desiredName);
  setDeep(localState, ["profile", "info_cache", "Default", "shortcut_name"], desiredName);
  setDeep(localState, ["profile", "info_cache", "Default", "user_name"], desiredName);
  // Color keys are best-effort (Chrome changes these frequently).
  setDeep(localState, ["profile", "info_cache", "Default", "profile_color"], desiredColor);
  setDeep(localState, ["profile", "info_cache", "Default", "user_color"], desiredColor);
  if (desiredColorInt != null) {
    // These are the fields Chrome actually uses for profile/avatar tinting.
    setDeep(
      localState,
      ["profile", "info_cache", "Default", "profile_color_seed"],
      desiredColorInt,
    );
    setDeep(
      localState,
      ["profile", "info_cache", "Default", "profile_highlight_color"],
      desiredColorInt,
    );
    setDeep(
      localState,
      ["profile", "info_cache", "Default", "default_avatar_fill_color"],
      desiredColorInt,
    );
    setDeep(
      localState,
      ["profile", "info_cache", "Default", "default_avatar_stroke_color"],
      desiredColorInt,
    );
  }
  safeWriteJson(localStatePath, localState);

  const prefs = preferencesRead.status === "ok" ? preferencesRead.value : {};
  setDeep(prefs, ["profile", "name"], desiredName);
  setDeep(prefs, ["profile", "profile_color"], desiredColor);
  setDeep(prefs, ["profile", "user_color"], desiredColor);
  if (desiredColorInt != null) {
    // Chrome refresh stores the autogenerated theme in these prefs (SkColor ints).
    setDeep(prefs, ["autogenerated", "theme", "color"], desiredColorInt);
    // User-selected browser theme color (pref name: browser.theme.user_color2).
    setDeep(prefs, ["browser", "theme", "user_color2"], desiredColorInt);
  }
  safeWriteJson(preferencesPath, prefs);

  try {
    fs.writeFileSync(decoratedMarkerPath(userDataDir), `${Date.now()}\n`, "utf-8");
  } catch {
    // ignore
  }
}

export function ensureProfileCleanExit(userDataDir: string) {
  const preferencesPath = path.join(userDataDir, "Default", "Preferences");
  const existing = readJsonRecord(preferencesPath);
  // Unreadable ≠ empty. Writing `{exit_type, exited_cleanly}` over a Preferences file we could
  // not look inside would drop every other setting in the profile.
  if (existing.status === "unreadable") {
    return;
  }
  const prefs = existing.status === "ok" ? existing.value : {};
  setDeep(prefs, ["exit_type"], "Normal");
  setDeep(prefs, ["exited_cleanly"], true);
  safeWriteJson(preferencesPath, prefs);
}
