#!/usr/bin/env node
/**
 * Persistence safety audit.
 *
 * Two failure shapes keep coming back in this codebase, and both destroy state rather than
 * merely report it wrong:
 *
 *  1. read-then-overwrite — a module reads a JSON state file with `loadJsonFile`, gets
 *     `undefined` when the file cannot be read or parsed, treats that as "empty", and then
 *     writes the empty state back over the only copy that existed.
 *  2. non-atomic-json-write — a module writes a `.json` state file with `writeFileSync`,
 *     which truncates first: a crash or ENOSPC part way through leaves a half-written file,
 *     which then reads as corrupt and feeds shape (1).
 *
 * This audit lists every such site and fails when a site is neither fixed nor explicitly
 * exempted, so a new state file cannot join the codebase silently.
 *
 * KNOWN BLIND SPOT: shape (1) is only recognised when the read goes through `loadJsonFile`. A
 * module with its *own* reader that swallows read/parse errors and returns `null` is invisible
 * here — `chrome.profile-decoration.ts` did exactly that and overwrote Chrome's `Preferences`
 * with a two-key object. Detecting that generically means guessing whether a `catch { return null
 * }` feeds a later write, which produces far more noise than signal. When you touch a module that
 * reads a JSON state file by hand, check the read side yourself: "cannot see it" and "it is
 * empty" must be different answers wherever the value is written back.
 *
 * Usage:
 *   tsx scripts/operator/lcx-persistence-safety-audit.ts
 *   tsx scripts/operator/lcx-persistence-safety-audit.ts --changed <path>
 *   tsx scripts/operator/lcx-persistence-safety-audit.ts --json
 *   tsx scripts/operator/lcx-persistence-safety-audit.ts --deep   # the blind spot, as a sweep
 */
import fs from "node:fs";
import path from "node:path";

type Finding = Readonly<{
  file: string;
  kind: "read-then-overwrite" | "non-atomic-json-write";
  detail: string;
}>;

/**
 * Sites that are known and accepted. Every entry must say *why* it is safe, because an
 * exemption that only says "known" is how a real defect becomes permanent background noise.
 */
const EXEMPTIONS: ReadonlyArray<{
  file: string;
  kind: Finding["kind"];
  why: string;
}> = [
  {
    file: "src/infra/json-file.ts",
    kind: "read-then-overwrite",
    why: "this module defines both primitives; loadJsonFile warns when a file cannot be read or parsed",
  },
  {
    file: "src/infra/json-file.ts",
    kind: "non-atomic-json-write",
    why: "saveJsonFile writes to a sibling temp file and renames it into place",
  },
  {
    file: "src/agents/subagent-registry.store.ts",
    kind: "read-then-overwrite",
    why: "uses loadJsonFileDetailed and refuses to write while the registry cannot be read",
  },
  {
    file: "src/agents/auth-profiles/store.ts",
    kind: "read-then-overwrite",
    why: "uses loadJsonFileDetailed and returns before writing while the store cannot be read",
  },
  {
    file: "src/agents/cli-credentials.ts",
    kind: "read-then-overwrite",
    why: "credentials are re-derivable from the system keychain; the source warns on read failure",
  },
  {
    file: "src/telegram/sticker-cache.ts",
    kind: "read-then-overwrite",
    why: "cache: losing it costs a refetch, and the source warns on read failure",
  },
  {
    file: "src/discord/monitor/thread-bindings.state.ts",
    kind: "read-then-overwrite",
    why: "bindings are rebuilt from the channel on next observe; the source warns on read failure",
  },
  {
    file: "src/providers/github-copilot-token.ts",
    kind: "read-then-overwrite",
    why: "token cache: a miss re-fetches the token; the source warns on read failure",
  },
  {
    file: "src/cli/secrets-cli.ts",
    kind: "non-atomic-json-write",
    why: "writes the plan file the operator asked for at --plan-out: an output artifact, regenerated by re-running the command, not state the runtime reads back",
  },
];

/**
 * Runtime state is written from `src` and from the bundled plugins under `extensions` — which is
 * where two credential stores were living, unexamined, until this audit was pointed at them.
 * Defaulting to `src` alone was a coverage gap, not a decision.
 *
 * Not included: `scripts/` (one-shot reports and build artifacts, regenerated every run — pass
 * `--roots scripts` to audit them), and `ui/` (browser-side; it stores state in the browser, not
 * in files this audit can reason about).
 */
const SOURCE_ROOTS = ["src", "extensions", "packages"];

function stripComments(code: string): string {
  return code.replace(/\/\*[\s\S]*?\*\//g, "").replace(/(^|[^:"'`])\/\/[^\n]*/g, "$1");
}

/**
 * Returns the argument list of every `name(...)` call in `code`.
 *
 * Heuristic on purpose: it walks brackets without understanding string literals, so an argument
 * containing an unbalanced bracket inside a string can mis-parse. The failure mode is a missed
 * call, never a fabricated one, and every hit is reviewed by a human before it is exempted.
 */
function callArgsOf(code: string, name: string): string[][] {
  const out: string[][] = [];
  const pattern = new RegExp(`\\b${name}\\s*\\(`, "g");
  let match: RegExpExecArray | null;
  while ((match = pattern.exec(code)) !== null) {
    const args: string[] = [];
    let index = match.index + match[0].length;
    let depth = 1;
    let current = "";
    while (index < code.length && depth > 0) {
      const ch = code[index];
      if (ch === "(" || ch === "[" || ch === "{") {
        depth += 1;
      } else if (ch === ")" || ch === "]" || ch === "}") {
        depth -= 1;
        if (depth === 0) {
          break;
        }
      } else if (ch === "," && depth === 1) {
        args.push(current);
        current = "";
        index += 1;
        continue;
      }
      current += ch;
      index += 1;
    }
    args.push(current);
    out.push(args);
  }
  return out;
}

/**
 * A bare identifier says nothing about *what* is being written. Follow it back to its
 * initializer so `temporaryPath` can be recognised as a temp file and `audioPath` as audio.
 */
function resolveTarget(code: string, target: string): string {
  const name = target.trim();
  if (!/^[A-Za-z_$][\w$]*$/.test(name)) {
    return name;
  }
  const pattern = new RegExp(`\\b(?:const|let|var)\\s+${name}\\s*=\\s*([^;\\n]+)`, "g");
  let resolved = name;
  let match: RegExpExecArray | null;
  while ((match = pattern.exec(code)) !== null) {
    resolved = `${name} = ${match[1]}`;
  }
  return resolved;
}

/**
 * The blind spot above, as a sweep rather than a gate: a module whose own reader swallows read or
 * parse failures and hands back nothing, and which also writes JSON. It cannot tell whether the
 * swallowed value feeds the later write — that judgement is a human's — so it never fails the
 * audit. Run it when you touch a module that reads state by hand.
 *
 * Deliberately *not* part of the default run: it names ~0.3% of `src`, and every name would need
 * an exemption, which is how a real signal turns into a list nobody reads.
 */
function deepCandidates(file: string, code: string): string[] {
  const swallows = /catch[\s\S]{0,120}?return\s+(null|undefined|\{\})/.test(code);
  const emptyCatch = /catch\s*(\([^)]*\))?\s*\{\s*\}/.test(code);
  const writes =
    /\bsaveJsonFile\s*\(/.test(code) || /writeFileSync\s*\([^)]*JSON\.stringify/.test(code);
  if (writes && (swallows || emptyCatch)) {
    return [
      `${file}: a read that fails is answered as "nothing there", and this module also writes JSON — check whether the swallowed value feeds that write`,
    ];
  }
  return [];
}

function auditFile(file: string, raw: string): Finding[] {
  const code = stripComments(raw);
  const findings: Finding[] = [];

  const readsJson = /\bloadJsonFile\s*\(/.test(code);
  const readsDetailed = /\bloadJsonFileDetailed\s*\(/.test(code);
  const writesJson = /\bsaveJsonFile\s*\(/.test(code);

  if (readsJson && writesJson && !readsDetailed) {
    findings.push({
      file,
      kind: "read-then-overwrite",
      detail:
        "reads with loadJsonFile and writes back with saveJsonFile; a file that cannot be read becomes an empty state that is then persisted over the original",
    });
  }

  // Judge each write by what it actually writes, not by what the rest of the module imports.
  // Two earlier versions of this check were file-level guesses and each had a blind spot:
  // requiring "no saveJsonFile anywhere" missed mixed modules, and requiring a literal `.json`
  // argument missed every write that goes through a variable — which is most of them.
  const unsafeTargets = callArgsOf(code, "writeFileSync")
    .filter((args) => /JSON\.stringify/.test(args[1] ?? ""))
    .map((args) => resolveTarget(code, args[0] ?? ""))
    .filter((resolved) => {
      // A sibling temp file is the atomic-write shape (`saveJsonFile` does the same thing): the
      // file only becomes visible to readers after the rename, so a crash costs nothing.
      return !/\.tmp/.test(resolved);
    });
  if (unsafeTargets.length > 0) {
    findings.push({
      file,
      kind: "non-atomic-json-write",
      detail: `writes ${unsafeTargets.join(" | ")} with writeFileSync instead of saveJsonFile; writeFileSync truncates first, so a crash mid-write leaves a truncated file behind`,
    });
  }

  return findings;
}

function collectFiles(roots: readonly string[] = SOURCE_ROOTS): string[] {
  const out: string[] = [];
  for (const root of roots) {
    const walk = (dir: string) => {
      let entries: fs.Dirent[];
      try {
        entries = fs.readdirSync(dir, { withFileTypes: true });
      } catch {
        return;
      }
      for (const entry of entries) {
        const full = path.join(dir, entry.name);
        if (entry.isDirectory()) {
          walk(full);
          continue;
        }
        if (!/\.(ts|mts)$/.test(entry.name)) {
          continue;
        }
        if (/\.(test|spec)\.ts$/.test(entry.name)) {
          continue;
        }
        // Shared fixtures used by tests, not production state writers.
        if (entry.name.endsWith(".test-helpers.ts")) {
          continue;
        }
        out.push(full);
      }
    };
    walk(root);
  }
  return out;
}

function isExempt(finding: Finding): boolean {
  return EXEMPTIONS.some((item) => item.file === finding.file && item.kind === finding.kind);
}

function main() {
  const argv = process.argv.slice(2);
  const asJson = argv.includes("--json");
  const asDeep = argv.includes("--deep");
  const changedIndex = argv.indexOf("--changed");
  const changed = changedIndex >= 0 ? argv[changedIndex + 1] : undefined;
  const rootsIndex = argv.indexOf("--roots");
  const roots =
    rootsIndex >= 0 ? argv.slice(rootsIndex + 1).filter((a) => !a.startsWith("--")) : SOURCE_ROOTS;

  const files = changed?.trim() ? [changed.trim()] : collectFiles(roots);
  const findings: Finding[] = [];
  const deep: string[] = [];
  for (const file of files) {
    let raw: string;
    try {
      raw = fs.readFileSync(file, "utf8");
    } catch {
      continue;
    }
    findings.push(...auditFile(file, raw));
    if (asDeep) {
      deep.push(...deepCandidates(file, stripComments(raw)));
    }
  }

  const unexempted = findings.filter((item) => !isExempt(item));
  const result = {
    ok: unexempted.length === 0,
    rule: "every JSON state file must survive a failed read and a half-finished write",
    scannedFiles: files.length,
    findings: findings.map((item) => ({
      ...item,
      exempted: isExempt(item),
    })),
    unexempted,
    deepCandidates: deep,
    nextAction:
      unexempted.length === 0
        ? "none"
        : "read the file with loadJsonFileDetailed (or stop writing back over an unreadable one), write with saveJsonFile, or add an exemption that states why it is safe",
  };

  if (asJson) {
    console.log(JSON.stringify(result, null, 2));
  } else {
    console.log(
      `persistence safety audit: ${result.ok ? "OK" : `${unexempted.length} finding(s)`} (scanned ${files.length} file(s))`,
    );
    for (const item of unexempted) {
      console.log(`  [${item.kind}] ${item.file}`);
      console.log(`      ${item.detail}`);
    }
    const exemptedCount = findings.length - unexempted.length;
    if (exemptedCount > 0) {
      console.log(`  (${exemptedCount} known and exempted site(s))`);
    }
    for (const item of deep) {
      console.log(`  [sweep] ${item}`);
    }
  }

  if (!result.ok) {
    process.exitCode = 1;
  }
}

main();
